on:
  push:
    tags:
      - v*
name: Demo App Android Release
jobs:
  build:
    name: Build APK and Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/subosito/flutter-action@v1
        with:
          flutter-version: '1.22.0-2.0.pre.105'
      - run: flutter pub get
      - run: flutter build apk
  - name: Release apk
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{secrets.CI_CD_SECRET}}